--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chad/.config/wpg/wallpapers/nice-city.jpg"

-- Special
background="#0d0c0f"
foreground="#e0d3bf"
cursor="#e0d3bf"

-- Colors
color0="#0d0c0f"
color1="#9C604A"
color2="#798574"
color3="#F0A215"
color4="#9C9172"
color5="#DFA365"
color6="#A8A68A"
color7="#e0d3bf"
color8="#9c9385"
color9="#9C604A"
color10="#798574"
color11="#F0A215"
color12="#9C9172"
color13="#DFA365"
color14="#A8A68A"
color15="#e0d3bf"
