# Shell variables
# Generated by 'wal'
wallpaper='/home/chad/.config/wpg/wallpapers/nice-city.jpg'

# Special
background='#0d0c0f'
foreground='#e0d3bf'
cursor='#e0d3bf'

# Colors
color0='#0d0c0f'
color1='#9C604A'
color2='#798574'
color3='#F0A215'
color4='#9C9172'
color5='#DFA365'
color6='#A8A68A'
color7='#e0d3bf'
color8='#9c9385'
color9='#9C604A'
color10='#798574'
color11='#F0A215'
color12='#9C9172'
color13='#DFA365'
color14='#A8A68A'
color15='#e0d3bf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
